#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Δβ-only AUC across (cohort × label tier).

Fills in the Δβ-only baseline rows missing from PAPER.md §5.2 (label-
granularity) and §5.3 (tissue). The validated-tier numbers are already
computed by `auc_uncertainty.py`; this script extends them to the
narrow (n=28) and wide (n=142) tiers on each cohort.

Implementation: streams each scored JSONL, computes the raw
Δβ = β_normal_mean − β_tumor_mean per record (None when either side is
missing; those records sort to the bottom under the same (-score, cid)
tie-break the benchmark uses), then computes AUC against each tier's
positives list via mid-rank Mann-Whitney.

Output: `examples/delta_beta_only_auc_sweep.tsv` and `.md`.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCORED = REPO / "data" / "derived"
OUT_TSV = REPO / "examples" / "delta_beta_only_auc_sweep.tsv"
OUT_MD = REPO / "examples" / "delta_beta_only_auc_sweep.md"

TIERS = [
    ("validated", "positives_roth_validated.txt"),
    ("narrow",    "positives_roth_narrow.txt"),
    ("wide",      "positives_roth_wide.txt"),
]

COHORTS = [
    ("GSE322563 HM450",     "scored_gse322563_differential.jsonl"),
    ("GSE322563 native v2", "scored_gse322563_native_differential.jsonl"),
    ("GSE77348",            "scored_surrogate_differential.jsonl"),
    ("GSE69914",            "scored_gse69914_differential.jsonl"),
]


def delta_beta_for(record: dict) -> float | None:
    obs = record.get("observation", {})
    bt, bn = obs.get("beta_tumor_mean"), obs.get("beta_normal_mean")
    if bt is None or bn is None:
        return None
    return bn - bt


def auc_midrank(scored_path: Path, positives: set[str]) -> tuple[float, int, int]:
    # Build list of (sort_key, cid): sort_key = -score; missing → +inf (sorts last).
    rows: list[tuple[float, str]] = []
    pos_scores: list[float] = []
    with scored_path.open() as fh:
        for line in fh:
            d = json.loads(line)
            cid = d["candidate"]["candidate_id"]
            db = delta_beta_for(d)
            sort_key = -db if db is not None else float("inf")
            rows.append((sort_key, cid))
            if cid in positives:
                pos_scores.append(db if db is not None else float("-inf"))
    n_total = len(rows)
    rows.sort()

    asc_scores = [-sk if sk != float("inf") else float("-inf") for sk, _ in rows]
    asc_scores.reverse()
    asc_cids = [cid for _, cid in rows]; asc_cids.reverse()

    n_pos = len(positives)
    n_neg = n_total - n_pos

    # Mid-rank AUC: sum of ascending mid-ranks of positives, minus n_pos(n_pos+1)/2,
    # divided by n_pos * n_neg.
    midrank_of: dict[str, float] = {}
    pos_rem = set(positives)
    i = 0
    while i < n_total and pos_rem:
        s = asc_scores[i]
        j = i
        while j < n_total and asc_scores[j] == s:
            j += 1
        mid = (i + 1 + j) / 2.0
        for k in range(i, j):
            cid = asc_cids[k]
            if cid in pos_rem:
                midrank_of[cid] = mid
                pos_rem.remove(cid)
                if not pos_rem:
                    break
        i = j

    sum_ranks = sum(midrank_of.values())
    auc = (sum_ranks - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg)
    return auc, n_pos, n_neg


def main() -> None:
    tier_positives = {
        tier: set(line.strip() for line in (SCORED / fname).read_text().splitlines() if line.strip())
        for tier, fname in TIERS
    }

    rows = []
    summary: dict[tuple[str, str], tuple[float, int, int]] = {}
    for cohort, fname in COHORTS:
        path = SCORED / fname
        if not path.exists():
            print(f"SKIP {path}")
            continue
        for tier, _ in TIERS:
            positives = tier_positives[tier]
            print(f"  Δβ-only AUC: {cohort} × {tier} (n_pos = {len(positives)}) ...")
            auc, n_pos, n_neg = auc_midrank(path, positives)
            summary[(cohort, tier)] = (auc, n_pos, n_neg)
            rows.append((cohort, tier, n_pos, n_neg, auc))
            print(f"    AUC = {auc:.4f}")

    OUT_TSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_TSV.open("w") as fh:
        fh.write("cohort\ttier\tn_pos\tn_neg\tdelta_beta_only_auc\n")
        for cohort, tier, n_pos, n_neg, auc in rows:
            fh.write(f"{cohort}\t{tier}\t{n_pos}\t{n_neg}\t{auc:.4f}\n")
    print(f"wrote {OUT_TSV}")

    md = ["# Δβ-only AUC across (cohort × label tier)",
          "",
          "Generated by `scripts/delta_beta_only_auc_sweep.py`.",
          "Raw Δβ = `β_normal_mean − β_tumor_mean`, no σ normalization.",
          "Mid-rank Mann-Whitney AUC under the benchmark's",
          "`candidate_id` ascending tie-break.",
          "",
          "| cohort | validated (n_pos=3) | narrow (n_pos=28) | wide (n_pos=142) |",
          "|---|---:|---:|---:|"]
    for cohort, _ in COHORTS:
        cells = []
        for tier, _ in TIERS:
            if (cohort, tier) in summary:
                auc, _, _ = summary[(cohort, tier)]
                cells.append(f"{auc:.3f}")
            else:
                cells.append("—")
        md.append(f"| **{cohort}** | " + " | ".join(cells) + " |")
    OUT_MD.write_text("\n".join(md))
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
