#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Aggregate per-cohort genome-wide gating TSVs into one combined table.

Consumes the per-cohort outputs of `genome_wide_tissue_gating.py` (which
emits AUC + tie-band + per-positive ranks for shipped V2.5 + three
gap_sigmoid bandwidths × {wg, chr5_6_10} subset for each cohort) and
emits a single Markdown panel showing:

  1. AUC per cohort × axis, WG vs chr5/6/10 — the denominator-robustness
     cross-cohort table.
  2. V2.5 − gap_sigmoid Δ AUC per cohort, WG — the tissue-specific
     underperformance headline reported once, for all cohorts.
  3. WG tie_band@100 per cohort × axis — usability of top-K as the
     denominator scales.
  4. Per-positive WG ranks under shipped V2.5 vs gap_sigmoid σ=0.0707
     per cohort — the reviewer's "rank robustness under chr5/6/10 vs
     genome-wide" check extended across all four cohorts.

Inputs: the four single-cohort gating TSVs (one per cohort).
Output: `examples/genome_wide_panel.md` + `.tsv`.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT_MD = REPO / "examples" / "genome_wide_panel.md"
OUT_TSV = REPO / "examples" / "genome_wide_panel.tsv"

AXES_SHOWN = ["shipped_v25", "gap_sigmoid_0.0500", "gap_sigmoid_0.0707", "gap_sigmoid_0.1000"]
AXIS_LABEL = {
    "shipped_v25": "V2.5 (shipped)",
    "gap_sigmoid_0.0500": "gap_sigmoid σ=0.05",
    "gap_sigmoid_0.0707": "gap_sigmoid σ=0.0707",
    "gap_sigmoid_0.1000": "gap_sigmoid σ=0.10",
}


def load_cohort(tsv_path: Path) -> dict:
    """Returns {(axis, subset): row_dict} for one cohort."""
    out: dict[tuple[str, str], dict] = {}
    with tsv_path.open() as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for row in reader:
            out[(row["axis"], row["subset"])] = row
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cohort", action="append", required=True,
                    metavar="LABEL:TSV_PATH",
                    help="Repeatable: e.g. --cohort 'GSE69914:examples/gse69914_wg_gating.tsv'")
    args = ap.parse_args()

    panels: list[tuple[str, dict]] = []
    for spec in args.cohort:
        label, _, path = spec.partition(":")
        panels.append((label, load_cohort(Path(path))))

    # Section 1: per-cohort × axis AUC (WG vs chr5/6/10).
    md = ["# Genome-wide panel — V2.5 vs gap_sigmoid across cohorts",
          "",
          "Generated by `scripts/genome_wide_panel.py`. Each cohort's",
          "per-axis AUC / tie-band / per-positive rank table is produced by",
          "`scripts/genome_wide_tissue_gating.py` from a scored JSONL on the",
          "frozen whole-genome catalogs (SHA256 `d20661c5…` HM450 path,",
          "SHA256 `39df8f0f…` native EPIC v2 path; full SHA256 lines and",
          "build commands in `data/derived/catalog_hg19_wg*.PROVENANCE.md`",
          "and `…PROVENANCE.sha256`).",
          "",
          "## Cross-cohort AUC table (validated labels, n_pos = 3)",
          ""]
    md.append("| cohort | subset | " + " | ".join(AXIS_LABEL[a] for a in AXES_SHOWN) + " |")
    md.append("|---|---|" + "---:|" * len(AXES_SHOWN))
    for label, rows in panels:
        for subset in ("wg", "chr5_6_10"):
            cells = []
            for axis in AXES_SHOWN:
                r = rows.get((axis, subset))
                cells.append(f"{float(r['auc']):.3f}" if r else "—")
            md.append(f"| **{label}** | {subset} | " + " | ".join(cells) + " |")

    # Section 2: V2.5 − gap_sigmoid σ=0.0707 Δ per cohort, WG only.
    md.extend(["",
               "## V2.5 − gap_sigmoid σ=0.0707 Δ AUC (WG only; positive = V2.5 better)",
               "",
               "| cohort | V2.5 AUC | gap_sigmoid AUC | Δ (V2.5 − gap_sigmoid) |",
               "|---|---:|---:|---:|"])
    for label, rows in panels:
        v25 = rows.get(("shipped_v25", "wg"))
        gs = rows.get(("gap_sigmoid_0.0707", "wg"))
        if v25 and gs:
            a1, a2 = float(v25["auc"]), float(gs["auc"])
            md.append(f"| **{label}** | {a1:.3f} | {a2:.3f} | **{a1 - a2:+.3f}** |")

    # Section 3: WG tie_band@100 per cohort × axis.
    md.extend(["",
               "## WG `tie_band@100` per cohort × axis",
               "",
               "| cohort | " + " | ".join(AXIS_LABEL[a] for a in AXES_SHOWN) + " |",
               "|---|" + "---:|" * len(AXES_SHOWN)])
    for label, rows in panels:
        cells = []
        for axis in AXES_SHOWN:
            r = rows.get((axis, "wg"))
            cells.append(f"{int(r['tie_band@100']):,}" if r else "—")
        md.append(f"| **{label}** | " + " | ".join(cells) + " |")

    # Section 4: per-positive WG ranks under V2.5 vs gap_sigmoid σ=0.0707.
    md.extend(["",
               "## Per-positive WG ranks: V2.5 vs gap_sigmoid σ=0.0707",
               "",
               "(1-based rank under `candidate_id` ascending tie-break.)",
               "",
               "| cohort | gene | V2.5 rank | gap_sigmoid rank | Δ (V2.5 − gap_sigmoid) |",
               "|---|---|---:|---:|---:|"])
    for label, rows in panels:
        v25 = rows.get(("shipped_v25", "wg"))
        gs = rows.get(("gap_sigmoid_0.0707", "wg"))
        if not (v25 and gs):
            continue
        for gene in ("ESR1", "EGFLAM", "GATA3"):
            key = f"{gene}_rank"
            r1 = int(v25[key]) if v25.get(key) else None
            r2 = int(gs[key]) if gs.get(key) else None
            delta = f"{r1 - r2:+,}" if (r1 is not None and r2 is not None) else "—"
            md.append(f"| {label} | *{gene}* | "
                      f"{(f'{r1:,}' if r1 else '—')} | "
                      f"{(f'{r2:,}' if r2 else '—')} | {delta} |")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(md))
    print(f"wrote {OUT_MD}")

    # TSV (long form).
    with OUT_TSV.open("w") as fh:
        fh.write("cohort\taxis\tsubset\tauc\ttie_band@20\ttie_band@100\ttie_band@1000"
                 "\tESR1_rank\tEGFLAM_rank\tGATA3_rank\n")
        for label, rows in panels:
            for (axis, subset), r in sorted(rows.items()):
                fh.write(
                    f"{label}\t{axis}\t{subset}\t{r['auc']}\t{r['tie_band@20']}"
                    f"\t{r['tie_band@100']}\t{r['tie_band@1000']}"
                    f"\t{r.get('ESR1_rank', '')}\t{r.get('EGFLAM_rank', '')}\t{r.get('GATA3_rank', '')}\n"
                )
    print(f"wrote {OUT_TSV}")


if __name__ == "__main__":
    main()
