#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Aggregate per-cohort limma-eBayes TSVs into a cross-cohort panel.

Consumes:
  - Per-cohort `limma_<cohort>_*.tsv` from scripts/limma_candidate_ranking.py
    (each produces rows for {limma_t, v25_diff} × {wg, chr5_6_10}).
  - Per-cohort `gse*_wg_gating.tsv` from scripts/genome_wide_tissue_gating.py
    (each produces rows for {shipped_v25, gap_sigmoid_*} × {wg, chr5_6_10}),
    already committed to `examples/`.

Emits a single markdown + TSV panel comparing limma-eBayes (probe-level
first, then candidate-mapped) against V2.5-diff and V2.5-sigmoid at WG
scale for the three primary cohorts (GSE322563 HM450, GSE322563 native
EPIC v2, GSE77348, GSE69914). Useful columns per cohort: AUC,
tie_band@100, ESR1/EGFLAM/GATA3 per-positive ranks.

Output: `examples/limma_cross_cohort_panel.{md,tsv}`.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
EX = REPO / "examples"
OUT_MD = EX / "limma_cross_cohort_panel.md"
OUT_TSV = EX / "limma_cross_cohort_panel.tsv"


def _read_limma_axes(path: Path) -> dict[tuple[str, str], dict]:
    """Returns {(axis, subset): row_dict} for a limma-candidate TSV."""
    out: dict[tuple[str, str], dict] = {}
    with path.open() as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for row in reader:
            out[(row["axis"], row["subset"])] = row
    return out


def _read_gating_axes(path: Path) -> dict[tuple[str, str], dict]:
    """Same shape as above, consumed from the V2.5 gating script TSVs."""
    out: dict[tuple[str, str], dict] = {}
    with path.open() as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for row in reader:
            out[(row["axis"], row["subset"])] = row
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--cohort", action="append", required=True,
        metavar="LABEL:LIMMA_TSV:GATING_TSV",
        help=("Repeatable: 'GSE322563 HM450:examples/limma_gse322563_hm450_wg.tsv:"
              "examples/gse322563_wg_gating.tsv'"))
    args = ap.parse_args()

    panels: list[tuple[str, dict, dict]] = []
    for spec in args.cohort:
        label, limma_path, gating_path = spec.split(":", 2)
        panels.append((label, _read_limma_axes(Path(limma_path)),
                       _read_gating_axes(Path(gating_path))))

    # Headline: AUC + tie_band@100 table per cohort × axis (WG only).
    md = ["# limma-eBayes cross-cohort panel (WG)",
          "",
          "Generated by `scripts/limma_cross_cohort_panel.py`. Aggregates the",
          "per-cohort limma-candidate ranking TSVs against the V2.5 gating",
          "TSVs to produce a 3-cohort × 3-axis comparison at whole-genome",
          "scale. Both axes are ranked on the **same frozen WG catalog**",
          "(HM450: SHA256 `d20661c5…`; native EPIC v2: `39df8f0f…`); limma",
          "t-stats come from the sample-level β matrix joined to the catalog",
          "via the V2.5 scored JSONL's `observation.probe_id` field",
          "(probe-level limma first, then candidate-mapped — per §7 Methods).",
          "",
          "## AUC + tie-band curve (validated labels, n_pos = 3)",
          "",
          "| cohort | axis | AUC | tie@20 | tie@100 | tie@500 | tie@1000 | P@100 [min, max] |",
          "|---|---|---:|---:|---:|---:|---:|---|"]
    tsv_rows = []
    for label, limma_rows, gating_rows in panels:
        for axis_label, src, key in (
            ("limma-eBayes", limma_rows, ("limma_t", "wg")),
            ("V2.5-diff (shipped)", limma_rows, ("v25_diff", "wg")),
            ("V2.5-sigmoid σ=0.0707", gating_rows, ("gap_sigmoid_0.0707", "wg")),
        ):
            r = src.get(key)
            if r is None:
                continue
            # Gating TSVs may not carry tie@500; only limma TSVs do.
            tb500 = r.get("tie@500", r.get("tie_band@500", "—"))
            tb20 = r.get("tie@20", r.get("tie_band@20", "—"))
            tb100 = r.get("tie@100", r.get("tie_band@100", "—"))
            tb1000 = r.get("tie@1000", r.get("tie_band@1000", "—"))
            auc_f = float(r["auc"])
            p_obs = r.get("P@100_obs", r.get("p100_obs", ""))
            p_min = r.get("P@100_min", r.get("p100_min", ""))
            p_max = r.get("P@100_max", r.get("p100_max", ""))
            try:
                p_min_f = float(p_min); p_max_f = float(p_max)
                p_str = f"[{p_min_f:.3f}, {p_max_f:.3f}]"
            except (ValueError, TypeError):
                p_str = "—"
            md.append(
                f"| **{label}** | {axis_label} | {auc_f:.3f} "
                f"| {_fmt_int(tb20)} | {_fmt_int(tb100)} | {_fmt_int(tb500)} | {_fmt_int(tb1000)} "
                f"| {p_str} |"
            )
            tsv_rows.append({
                "cohort": label, "axis": axis_label, "subset": "wg",
                "auc": auc_f, "tb20": tb20, "tb100": tb100, "tb500": tb500, "tb1000": tb1000,
                "p100_obs": p_obs, "p100_min": p_min, "p100_max": p_max,
            })

    # Per-positive rank table (limma vs V2.5-sigmoid only — the head-to-head
    # between the DMR-baseline and the current recommendation).
    md.extend(["",
               "## Per-positive WG ranks: limma-eBayes vs V2.5-sigmoid σ=0.0707",
               "",
               "(1-based, `candidate_id` ascending tie-break.)",
               "",
               "| cohort | gene | limma rank | V2.5-sigmoid rank | Δ (limma − sigmoid) |",
               "|---|---|---:|---:|---:|"])
    for label, limma_rows, gating_rows in panels:
        lr = limma_rows.get(("limma_t", "wg"))
        gr = gating_rows.get(("gap_sigmoid_0.0707", "wg"))
        if not (lr and gr):
            continue
        for gene in ("ESR1", "EGFLAM", "GATA3"):
            key = f"{gene}_rank"
            lv = lr.get(key, "")
            gv = gr.get(key, "")
            try:
                li = int(lv); gi = int(gv)
                delta = f"{li - gi:+,}"
                md.append(f"| {label} | *{gene}* | {li:,} | {gi:,} | {delta} |")
            except (ValueError, TypeError):
                md.append(f"| {label} | *{gene}* | {lv or '—'} | {gv or '—'} | — |")

    OUT_MD.write_text("\n".join(md))
    print(f"wrote {OUT_MD}")

    with OUT_TSV.open("w", newline="") as fh:
        if tsv_rows:
            writer = csv.DictWriter(fh, fieldnames=list(tsv_rows[0].keys()), delimiter="\t")
            writer.writeheader()
            writer.writerows(tsv_rows)
    print(f"wrote {OUT_TSV}")


def _fmt_int(x) -> str:
    if x is None or x == "" or x == "—":
        return "—"
    try:
        return f"{int(x):,}"
    except (ValueError, TypeError):
        return str(x)


if __name__ == "__main__":
    main()
