#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Paired per-positive rank-lift: V2.5 vs Δβ-only.

The permutation null in §5.1.2 tests each axis against uniformly-
random 3-record positive triples drawn from the full candidate set.
That answers "does the axis separate these 3 positives from the rest?"
but does not directly compare V2.5 against Δβ-only *on the same
positives and the same negative universe*.

This script runs the corresponding paired comparison: for each primary
cohort, for each of the 3 Roth-validated positives, report its V2.5
rank and Δβ-only rank, the per-positive difference (Δβ-only rank −
V2.5 rank, positive = V2.5 ranks the positive higher), and the
aggregate lift (sum across positives).

Statistical summary: with n_pos = 3 the natural paired permutation
test is a sign-flip null that randomly swaps the V2.5 and Δβ-only
rank assignments at each positive (2³ = 8 equiprobable outcomes).
The resolution floor is p = 1/8 ≈ 0.125 one-sided when all three
signs agree. We report p_exact and the per-positive 3/3 agreement
explicitly; interpret descriptively, not inferentially (n_pos = 3
makes any paired test resolution-limited).

Ranks are looked up from `examples/validated_positive_ranks.tsv` —
the committed per-positive rank table built by
`scripts/validated_positive_ranks.py`. This script re-computes
nothing; it just re-reads the committed ranks and emits the paired
summary.

Output: `examples/paired_rank_lift_v25_vs_dbeta.md` + `.tsv`.
"""

from __future__ import annotations

import csv
import itertools
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RANKS = REPO / "examples" / "validated_positive_ranks.tsv"
OUT_TSV = REPO / "examples" / "paired_rank_lift_v25_vs_dbeta.tsv"
OUT_MD = REPO / "examples" / "paired_rank_lift_v25_vs_dbeta.md"

# cohort labels as they appear in the source TSV
COHORTS = ["GSE322563 HM450", "GSE322563 native v2", "GSE77348"]
GENES = ["ESR1", "EGFLAM", "GATA3"]


def load_ranks() -> dict[tuple[str, str, str], int]:
    """Return {(cohort, axis, gene): rank_1_based}."""
    out: dict[tuple[str, str, str], int] = {}
    with RANKS.open() as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for row in reader:
            out[(row["cohort"], row["axis"], row["gene"])] = int(row["rank"])
    return out


def sign_flip_p_value(diffs: list[int]) -> tuple[float, float]:
    """Exact two-sided and one-sided p under the independent-sign-flip null.

    For n_pos diffs, null enumerates all 2^n_pos sign patterns. The test
    statistic is sum(diffs). Two-sided p = Pr(|null_sum| ≥ |observed_sum|);
    one-sided p (V2.5 > Δβ-only) = Pr(null_sum ≥ observed_sum).
    """
    abs_diffs = [abs(d) for d in diffs]
    observed = sum(diffs)
    signs = list(itertools.product((-1, 1), repeat=len(diffs)))
    null_sums = [sum(s * a for s, a in zip(sign, abs_diffs)) for sign in signs]
    n = len(signs)
    one_sided = sum(1 for x in null_sums if x >= observed) / n
    two_sided = sum(1 for x in null_sums if abs(x) >= abs(observed)) / n
    return one_sided, two_sided


def main() -> None:
    ranks = load_ranks()
    rows = []
    summary = {}
    for cohort in COHORTS:
        diffs = []
        per_gene = []
        for gene in GENES:
            r_v25 = ranks[(cohort, "V2.5 diff", gene)]
            r_db = ranks[(cohort, "Δβ-only", gene)]
            diff = r_db - r_v25
            diffs.append(diff)
            per_gene.append((gene, r_v25, r_db, diff))
        total = sum(diffs)
        n_v25_wins = sum(1 for d in diffs if d > 0)
        one_sided, two_sided = sign_flip_p_value(diffs)
        summary[cohort] = {
            "per_gene": per_gene, "total_lift": total,
            "n_v25_wins": n_v25_wins, "n_total": len(diffs),
            "p_one_sided": one_sided, "p_two_sided": two_sided,
        }
        for gene, r_v25, r_db, diff in per_gene:
            rows.append((cohort, gene, r_v25, r_db, diff))

    OUT_TSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_TSV.open("w") as fh:
        fh.write("cohort\tgene\tV2.5_rank\tdelta_beta_only_rank\trank_diff\n")
        for cohort, gene, rv, rd, d in rows:
            fh.write(f"{cohort}\t{gene}\t{rv}\t{rd}\t{d}\n")
    print(f"wrote {OUT_TSV}")

    md = ["# Paired per-positive rank-lift: V2.5 vs Δβ-only",
          "",
          "Generated by `scripts/paired_rank_lift_v25_vs_dbeta.py` from",
          "`examples/validated_positive_ranks.tsv`.",
          "",
          "Per-positive rank (1-based under `candidate_id` ascending tie-break)",
          "for the three Roth-validated positives under V2.5 vs raw Δβ-only, on",
          "each primary matched cell-line cohort. `rank_diff = r_Δβ − r_V2.5`",
          "so positive = V2.5 ranks the positive higher.",
          "",
          "Paired sign-flip permutation null (2³ = 8 outcomes): randomly swap the",
          "V2.5 and Δβ-only rank assignments at each positive independently.",
          "With n_pos = 3 the resolution floor is p_one_sided = 1/8 = 0.125 when",
          "all three per-positive rank differences have the same sign. **Interpret",
          "descriptively, not inferentially.**",
          ""]
    for cohort in COHORTS:
        s = summary[cohort]
        md.append(f"## {cohort}")
        md.append("")
        md.append("| gene | V2.5 rank | Δβ-only rank | rank lift (Δβ−V2.5) |")
        md.append("|---|---:|---:|---:|")
        for gene, r_v25, r_db, diff in s["per_gene"]:
            arrow = "↑" if diff > 0 else ("↓" if diff < 0 else "=")
            md.append(f"| *{gene}* | {r_v25:,} | {r_db:,} | {arrow} **{diff:+,}** |")
        md.append("")
        md.append(f"- V2.5 ranks {s['n_v25_wins']}/{s['n_total']} positives higher than Δβ-only.")
        md.append(f"- Aggregate rank lift (sum of rank_diff): **{s['total_lift']:+,}** positions.")
        md.append(f"- Sign-flip null one-sided p = {s['p_one_sided']:.3f}; two-sided p = {s['p_two_sided']:.3f}.")
        md.append("")
    OUT_MD.write_text("\n".join(md))
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
