#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""σ_floor binding rate per cohort.

For each cohort, report the fraction of scored records where the
per-side σ_floor is the binding constraint on σ_Δ — i.e. where
`max(σ_k, σ_floor) == σ_floor` for at least one side (k ∈ {tumor,
normal}), meaning the per-side IQR-derived σ is below the floor and
the floor is what's determining the denominator of `p_diff`.

Two rates are reported:

- `pct_either_binds` — fraction of observed records (both β means
  present) where σ_floor binds on *either* side. This is the
  upper-bound on "σ_floor is involved".
- `pct_both_bind` — fraction where σ_floor binds on *both* sides.
  This is the lower-bound "σ_floor fully determines σ_Δ".

Records with one or both β means missing are excluded from the
denominator — σ_floor does not affect their `p_diff` (which is
definitionally 0.0 when either side is missing).

Output: `examples/sigma_floor_binding_rate.tsv` + `.md`.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCORED = REPO / "data" / "derived"
OUT_TSV = REPO / "examples" / "sigma_floor_binding_rate.tsv"
OUT_MD = REPO / "examples" / "sigma_floor_binding_rate.md"

_IQR_TO_STDEV = 1.349
SIGMA_FLOOR = 0.05

COHORTS = [
    ("GSE322563 HM450",     "scored_gse322563_differential.jsonl"),
    ("GSE322563 native v2", "scored_gse322563_native_differential.jsonl"),
    ("GSE77348",            "scored_surrogate_differential.jsonl"),
    ("GSE69914",            "scored_gse69914_differential.jsonl"),
]


def count_for(path: Path) -> dict:
    total = observed = floor_either = floor_both = floor_tumor = floor_normal = 0
    with path.open() as fh:
        for line in fh:
            total += 1
            obs = json.loads(line).get("observation", {})
            mu_t, mu_n = obs.get("beta_tumor_mean"), obs.get("beta_normal_mean")
            if mu_t is None or mu_n is None:
                continue
            observed += 1
            q25_t, q75_t = obs.get("beta_tumor_q25"), obs.get("beta_tumor_q75")
            q25_n, q75_n = obs.get("beta_normal_q25"), obs.get("beta_normal_q75")
            sigma_t = (q75_t - q25_t) / _IQR_TO_STDEV if (q25_t is not None and q75_t is not None) else 0.0
            sigma_n = (q75_n - q25_n) / _IQR_TO_STDEV if (q25_n is not None and q75_n is not None) else 0.0
            t_binds = sigma_t < SIGMA_FLOOR
            n_binds = sigma_n < SIGMA_FLOOR
            if t_binds:
                floor_tumor += 1
            if n_binds:
                floor_normal += 1
            if t_binds or n_binds:
                floor_either += 1
            if t_binds and n_binds:
                floor_both += 1
    return dict(total=total, observed=observed,
                floor_either=floor_either, floor_both=floor_both,
                floor_tumor=floor_tumor, floor_normal=floor_normal)


def main() -> None:
    rows = []
    for cohort, fname in COHORTS:
        path = SCORED / fname
        if not path.exists():
            print(f"SKIP missing: {path}")
            continue
        print(f"  counting σ_floor binding on {cohort} ...")
        c = count_for(path)
        print(f"    observed: {c['observed']:,}; either-side binds: {c['floor_either']:,} "
              f"({100*c['floor_either']/c['observed']:.1f}%)")
        rows.append((cohort, c))

    OUT_TSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_TSV.open("w") as fh:
        fh.write("cohort\ttotal_records\tobserved_records\tfloor_tumor\tfloor_normal\tfloor_either\tfloor_both\tpct_either\tpct_both\n")
        for cohort, c in rows:
            pct_either = 100 * c["floor_either"] / c["observed"] if c["observed"] else 0.0
            pct_both = 100 * c["floor_both"] / c["observed"] if c["observed"] else 0.0
            fh.write(f"{cohort}\t{c['total']}\t{c['observed']}\t{c['floor_tumor']}\t{c['floor_normal']}\t{c['floor_either']}\t{c['floor_both']}\t{pct_either:.2f}\t{pct_both:.2f}\n")
    print(f"wrote {OUT_TSV}")

    md = ["# σ_floor binding rate per cohort",
          "",
          "Generated by `scripts/sigma_floor_binding_rate.py`. σ_floor = 0.05.",
          "",
          "For each observed record (both β means present), we check whether",
          "`σ_k = IQR_k / 1.349 < σ_floor` on each side. Denominator is observed",
          "records only — records with one or both sides missing are excluded",
          "(p_diff is 0 by definition there).",
          "",
          "| cohort | observed records | σ_floor binds either side | σ_floor binds both sides |",
          "|---|---:|---:|---:|"]
    for cohort, c in rows:
        if c["observed"] == 0:
            md.append(f"| {cohort} | 0 | — | — |")
            continue
        pct_either = 100 * c["floor_either"] / c["observed"]
        pct_both = 100 * c["floor_both"] / c["observed"]
        md.append(
            f"| **{cohort}** | {c['observed']:,} | "
            f"{c['floor_either']:,} ({pct_either:.1f}%) | "
            f"{c['floor_both']:,} ({pct_both:.1f}%) |"
        )
    OUT_MD.write_text("\n".join(md))
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
